repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: ['--fix', '--unsafe-fixes']
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        files: ^backend/.*
        args: ['--rcfile=pyproject.toml']
        require_serial: true
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        files: ^backend/.*
        require_serial: true
